# Generated by Django 4.2.7 on 2024-01-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_post_delete_matrixdat_datainsert_play2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='todaysmood',
        ),
    ]
