# Generated by Django 4.2.7 on 2024-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_rename_post_post_todaysmood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pocet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
